# GET http://localhost:3001/users HTTP/1.1

POST http://localhost:3001/users HTTP/1.1
    "first_name": "Willy",
    "last_name": "Wonka",
    "email": "willyW@email.com",
    "password": "h4f4h51453",
    "role": "estudiante"

Content-Type: application/json